name: Run Notebook

on:
  push:
    branches: [main]

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Notebook
      run: |
        pip install nbconvert
        jupyter nbconvert --execute --to notebook notebooks/Heart_Disease_RF_Tuning.ipynb --output executed_notebook.ipynb
